import "../assets/CSS/globals.css";
import { Inter } from "next/font/google";
import { Providers } from "@/redux/provider";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar company={""} />
        <main className="min-h-screen bg-secondary p-4 md:p-8">
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  );
}